"""empty message

Revision ID: 2f74ce15ae6f
Revises: 
Create Date: 2020-11-18 09:04:06.715256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f74ce15ae6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('friend_name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_room', sa.String(length=30), nullable=False),
    sa.Column('id_user', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_plant', sa.String(length=45), nullable=False),
    sa.Column('tipo_plant', sa.String(length=45), nullable=False),
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_plant')
    )
    op.create_table('plants__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.Integer(), nullable=False),
    sa.Column('humidity_sensor', sa.Integer(), nullable=False),
    sa.Column('temperature_sensor', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=45), nullable=False),
    sa.Column('id_plant_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_plant_name'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants__tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_tipo', sa.String(length=45), nullable=False),
    sa.Column('humidity_ideal', sa.Integer(), nullable=False),
    sa.Column('temperature_ideal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name_tipo'], ['plants.tipo_plant'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants__tipo')
    op.drop_table('plants__time')
    op.drop_table('plants')
    op.drop_table('room')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
