"""empty message

Revision ID: 78d4f56356c1
Revises: 93555bc8aa90
Create Date: 2020-12-08 14:15:28.936278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78d4f56356c1'
down_revision = '93555bc8aa90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'sensor_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'sensor_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
