"""empty message

Revision ID: 93555bc8aa90
Revises: 5908e5561940
Create Date: 2020-12-01 14:56:43.187310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93555bc8aa90'
down_revision = '5908e5561940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plants_ibfk_2', 'plants', type_='foreignkey')
    op.create_foreign_key(None, 'plants', 'room', ['id_room'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.create_foreign_key('plants_ibfk_2', 'plants', 'room', ['id_room'], ['id'])
    # ### end Alembic commands ###
