"""empty message

Revision ID: a42a40dfde53
Revises: 
Create Date: 2020-11-24 10:08:23.013285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42a40dfde53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants__grow__phase',
    sa.Column('name_grow_phase', sa.Enum(), nullable=False),
    sa.Column('humidity_max_ideal', sa.Integer(), nullable=False),
    sa.Column('humidity_min_ideal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name_grow_phase'], ['plants.grow_phase'], ),
    sa.PrimaryKeyConstraint('name_grow_phase')
    )
    op.create_table('plants__sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_number', sa.Integer(), nullable=False),
    sa.Column('humidity_sensor', sa.Integer(), nullable=False),
    sa.Column('temperature_sensor', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_number'], ['plants.sensor_number'], ),
    sa.PrimaryKeyConstraint('id', 'sensor_number')
    )
    op.create_table('plants__tipo',
    sa.Column('name_tipo', sa.String(length=45), nullable=False),
    sa.Column('temperature_max_ideal', sa.Integer(), nullable=False),
    sa.Column('temperature_min_ideal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name_tipo'], ['plants.tipo_plant'], ),
    sa.PrimaryKeyConstraint('name_tipo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants__tipo')
    op.drop_table('plants__sensors')
    op.drop_table('plants__grow__phase')
    # ### end Alembic commands ###